package ExceptionHandling;

public class ArrayException {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		try {
		int arr[]= {10,200,30,40,42};
		
		System.out.println(arr[10]);
		
		
		
		}
		catch(ArrayIndexOutOfBoundsException e)
		{
			
			System.out.println("Size of the array is greater"+e);
			
		}
		
		
		

	}

}
